.........C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:293: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
............................................................................................................................................................................................................................................................................................................................................................................................................EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE..........................................................................................................................................................................................................................................................................C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:282: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zv = np.partition(x, -k, axis=axis)[idx]
C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
......C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:282: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zv = np.partition(x, -k, axis=axis)[idx]
C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
......C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:282: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zv = np.partition(x, -k, axis=axis)[idx]
C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
......C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:282: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zv = np.partition(x, -k, axis=axis)[idx]
C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
.........................................................................................................................................C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
............C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
....C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zi = np.argpartition(x, -k, axis=axis)[idx]
...
======================================================================
ERROR: test_combined_1d_00 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_01 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_02 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_03 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_04 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_05 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_06 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_07 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_08 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_09 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_10 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_11 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_12 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_13 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_14 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_15 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_16 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_17 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_18 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_19 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_20 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_21 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_22 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_23 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_24 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_25 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_26 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_27 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_28 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_29 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_30 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_31 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_32 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_33 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_34 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_35 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_36 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_37 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_38 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_39 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_40 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_41 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_42 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_43 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_44 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_45 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_46 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_47 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_48 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_49 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_50 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_51 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_52 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_53 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_54 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_55 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_56 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_57 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_58 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_59 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_60 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_61 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_62 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_63 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_64 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_65 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_66 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_67 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_68 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_69 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_70 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_71 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

======================================================================
ERROR: test_combined_1d_72 (test_sort.Test_TopK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_sort.py", line 348, in test_combined_1d
    yv, yi = topk_and_argtopk(x, k, sorted=sorted, idx_dtype=idx_dtype)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 563, in topk_and_argtopk
    idx_dtype=idx_dtype)(x, kth)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\sort.py", line 399, in make_node
    ' expected integer within [%d, %d]' % (-ndim, ndim - 1))
IndexError: "axis" parameter out of range, expected integer within [-1, 0]

----------------------------------------------------------------------
Ran 918 tests in 54.825s

FAILED (errors=73)
