..E.
======================================================================
ERROR: test_infer_shape (test_ops.OpDecoratorTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_ops.py", line 64, in test_infer_shape
    @as_op([dmatrix, dvector], dvector, infer_shape)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 622, in as_op
    raise TypeError("infer_shape needs to be a callable")
TypeError: infer_shape needs to be a callable

----------------------------------------------------------------------
Ran 4 tests in 0.719s

FAILED (errors=1)
