................EEE........EE..F..FFEEE
======================================================================
ERROR: test_fwd (test_abstract_conv.TestAsymmetricPadding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (2, 4, 6, 5), but the given topgrad has shape (2, 4, 6, 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1998, in test_fwd
    utt.verify_grad(asymmetric_conv_op, [img, kern], mode=self.mode, eps=1)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tests\unittest_tools.py", line 92, in verify_grad
    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gradient.py", line 1780, in verify_grad
    analytic_grad = grad_fn(*[p.copy() for p in pt])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: ('invalid input_shape for gradInputs: the given input_shape would produce an output of shape (2, 4, 6, 5), but the given topgrad has shape (2, 4, 6, 6)\nApply node that caused the error: AbstractConv2d_gradInputs{convdim=2, border_mode=((1, 2), (2, 1)), subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None), filter_dilation=(1, 1), num_groups=1, unshared=False}(input 1, Elemwise{mul}.0, Subtensor{int64::}.0)\nToposort index: 9\nInputs types: [TensorType(float64, 4D), TensorType(float64, 4D), TensorType(int64, vector)]\nInputs shapes: [(4, 2, 2, 2), (2, 4, 6, 6), (2,)]\nInputs strides: [(64, 32, 16, 8), (1152, 288, 48, 8), (8,)]\nInputs values: [\'not shown\', \'not shown\', array([4, 4], dtype=int64)]\nOutputs clients: [[\'output\']]\n\nBacktrace when the node is created(use Theano flag traceback.limit=N to make it longer):\n  File "C:\\Users\\mutation\\Desktop\\theano-testcase\\tests\\test_abstract_conv.py", line 1998, in test_fwd\n    utt.verify_grad(asymmetric_conv_op, [img, kern], mode=self.mode, eps=1)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\tests\\unittest_tools.py", line 92, in verify_grad\n    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1770, in verify_grad\n    disconnected_inputs=\'ignore\')\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 605, in grad\n    grad_dict, wrt, cost_name)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in _populate_grad_dict\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in <listcomp>\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1326, in access_grad_cache\n    term = access_term_cache(node)[idx]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1162, in access_term_cache\n    new_output_grads)\n\nHINT: Use the Theano flag \'exception_verbosity=high\' for a debugprint and storage map footprint of this apply node.', '\nThe error happened with the following inputs:', [array([[[[0.46848893, 0.23431308, 0.08982494, 0.67940357],
         [0.65592832, 0.0039444 , 0.06654134, 0.00112109],
         [0.66608382, 0.38565116, 0.09405827, 0.45856757],
         [0.64434173, 0.59499774, 0.79060307, 0.79996907]],

        [[0.67969792, 0.43875185, 0.26235889, 0.23652188],
         [0.83900208, 0.36874334, 0.61918838, 0.46656433],
         [0.49250063, 0.71862211, 0.65415881, 0.9665017 ],
         [0.38957233, 0.97017219, 0.36057961, 0.56184234]]],


       [[[0.03133558, 0.30480028, 0.07269465, 0.46721993],
         [0.41345069, 0.42228271, 0.79491031, 0.05651855],
         [0.89718201, 0.31869638, 0.36398678, 0.70548804],
         [0.23103497, 0.54827043, 0.3195602 , 0.7302113 ]],

        [[0.94257233, 0.77442252, 0.86379077, 0.82903615],
         [0.81379647, 0.63166234, 0.68810426, 0.09505542],
         [0.87637271, 0.83280508, 0.42067349, 0.77582558],
         [0.49097792, 0.52603444, 0.71381734, 0.12317237]]]]), array([[[[0.45279855, 0.14136043],
         [0.34007602, 0.23354548]],

        [[0.50744427, 0.42741471],
         [0.53647236, 0.8690842 ]]],


       [[[0.84334885, 0.04136067],
         [0.07753699, 0.36800508]],

        [[0.74431332, 0.38844287],
         [0.14635092, 0.37732909]]],


       [[[0.37146278, 0.93263398],
         [0.87870934, 0.63540289]],

        [[0.07311182, 0.84731036],
         [0.85063229, 0.33730248]]],


       [[[0.64449643, 0.8330261 ],
         [0.53444522, 0.66108231]],

        [[0.59079962, 0.408068  ],
         [0.22967834, 0.68915406]]]])], '\nThe value of eps is:', 1, '\nThe out_type is:', None)

======================================================================
ERROR: test_gradinput (test_abstract_conv.TestAsymmetricPadding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (2, 4, 6, 5), but the given topgrad has shape (2, 4, 6, 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 2056, in test_gradinput
    asymmetric_output = asymmetric_func(kern, top)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (2, 4, 6, 5), but the given topgrad has shape (2, 4, 6, 6)
Apply node that caused the error: AbstractConv2d_gradInputs{convdim=2, border_mode=((1, 2), (2, 1)), subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None), filter_dilation=(1, 1), num_groups=1, unshared=False}(kern, top, TensorConstant{(2,) of 4})
Toposort index: 0
Inputs types: [TensorType(float64, 4D), TensorType(float64, 4D), TensorType(int32, vector)]
Inputs shapes: [(4, 2, 2, 2), (2, 4, 6, 6), (2,)]
Inputs strides: [(64, 32, 16, 8), (1152, 288, 48, 8), (4,)]
Inputs values: ['not shown', 'not shown', array([4, 4])]
Outputs clients: [['output']]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 2052, in test_gradinput
    asymmetric_out_sym = asymmetric_conv_op(kern_sym, top_sym, imshp[-2:])

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

======================================================================
ERROR: test_gradweight (test_abstract_conv.TestAsymmetricPadding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (2, 4, 6, 5), but the given topgrad has shape (2, 4, 6, 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 2038, in test_gradweight
    utt.verify_grad(conv_gradweight, [img, top], mode=self.mode, eps=1)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tests\unittest_tools.py", line 92, in verify_grad
    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gradient.py", line 1780, in verify_grad
    analytic_grad = grad_fn(*[p.copy() for p in pt])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: ('invalid input_shape for gradInputs: the given input_shape would produce an output of shape (2, 4, 6, 5), but the given topgrad has shape (2, 4, 6, 6)\nApply node that caused the error: AbstractConv2d_gradInputs{convdim=2, border_mode=((1, 2), (2, 1)), subsample=(1, 1), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None), filter_dilation=(1, 1), num_groups=1, unshared=False}(Elemwise{mul}.0, input 1, Subtensor{int64::}.0)\nToposort index: 9\nInputs types: [TensorType(float64, 4D), TensorType(float64, 4D), TensorType(int64, vector)]\nInputs shapes: [(4, 2, 2, 2), (2, 4, 6, 6), (2,)]\nInputs strides: [(64, 32, 16, 8), (1152, 288, 48, 8), (8,)]\nInputs values: [\'not shown\', \'not shown\', array([4, 4], dtype=int64)]\nOutputs clients: [[\'output\']]\n\nBacktrace when the node is created(use Theano flag traceback.limit=N to make it longer):\n  File "C:\\Users\\mutation\\Desktop\\theano-testcase\\tests\\test_abstract_conv.py", line 2038, in test_gradweight\n    utt.verify_grad(conv_gradweight, [img, top], mode=self.mode, eps=1)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\tests\\unittest_tools.py", line 92, in verify_grad\n    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1770, in verify_grad\n    disconnected_inputs=\'ignore\')\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 605, in grad\n    grad_dict, wrt, cost_name)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in _populate_grad_dict\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in <listcomp>\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1326, in access_grad_cache\n    term = access_term_cache(node)[idx]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1162, in access_term_cache\n    new_output_grads)\n\nHINT: Use the Theano flag \'exception_verbosity=high\' for a debugprint and storage map footprint of this apply node.', '\nThe error happened with the following inputs:', [array([[[[0.08951013, 0.44073919, 0.10495735, 0.68183782],
         [0.31150283, 0.66919707, 0.98841389, 0.3930208 ],
         [0.29226331, 0.46756277, 0.29031652, 0.84918804],
         [0.712163  , 0.34929942, 0.45208028, 0.42877569]],

        [[0.60850074, 0.73609298, 0.35253624, 0.35601395],
         [0.59136704, 0.82312425, 0.65087742, 0.57607829],
         [0.50310554, 0.09924719, 0.27264032, 0.03344569],
         [0.70604898, 0.64870168, 0.41037587, 0.00773816]]],


       [[[0.58266509, 0.74501867, 0.92419115, 0.09815225],
         [0.03236548, 0.106822  , 0.17913859, 0.17518167],
         [0.20578784, 0.3271364 , 0.4913322 , 0.48687574],
         [0.5032574 , 0.28815934, 0.47458508, 0.06431285]],

        [[0.3308476 , 0.48623288, 0.29528988, 0.37818203],
         [0.5417532 , 0.40010546, 0.76240955, 0.47955264],
         [0.15861623, 0.13080003, 0.48172727, 0.24642311],
         [0.92249391, 0.57461442, 0.07461399, 0.37269671]]]]), array([[[[0.19748517, 0.63225866, 0.94114428, 0.82023108, 0.26307149,
          0.86991022],
         [0.39742133, 0.88811711, 0.71855562, 0.66002236, 0.97249178,
          0.09441107],
         [0.30465039, 0.0762231 , 0.78761657, 0.64670505, 0.96267341,
          0.95592698],
         [0.86098628, 0.95262915, 0.04407321, 0.77759974, 0.57376583,
          0.71569645],
         [0.15618335, 0.53053071, 0.34794832, 0.14246731, 0.83683726,
          0.39317949],
         [0.81061229, 0.61630338, 0.63907216, 0.12253074, 0.35538833,
          0.04429985]],

        [[0.15362478, 0.19122078, 0.82903655, 0.96854568, 0.43481821,
          0.31767392],
         [0.77021078, 0.28244732, 0.38467936, 0.22577154, 0.59839337,
          0.93039134],
         [0.13158445, 0.31302627, 0.36936329, 0.86175496, 0.27551035,
          0.8822734 ],
         [0.51128198, 0.77603478, 0.05065324, 0.01078841, 0.36965792,
          0.56117075],
         [0.29515017, 0.40854509, 0.2270829 , 0.07465744, 0.89673015,
          0.65823359],
         [0.58300058, 0.34835623, 0.6598614 , 0.32660515, 0.69166244,
          0.21705726]],

        [[0.71085574, 0.49495187, 0.85774804, 0.59884657, 0.70694106,
          0.24421088],
         [0.51280413, 0.1258849 , 0.47038107, 0.39499497, 0.16628639,
          0.48889568],
         [0.66479674, 0.33969304, 0.31799934, 0.2297029 , 0.05338387,
          0.66195348],
         [0.11347362, 0.16848512, 0.9107186 , 0.34193589, 0.46852936,
          0.06549789],
         [0.94881844, 0.45298171, 0.52923887, 0.49652562, 0.45500212,
          0.59928577],
         [0.26176364, 0.86341968, 0.40887141, 0.52253318, 0.52862963,
          0.02526051]],

        [[0.69934208, 0.43672267, 0.06465723, 0.30489059, 0.11921288,
          0.40982387],
         [0.87844812, 0.36521498, 0.779061  , 0.72191177, 0.74037803,
          0.38926291],
         [0.38578523, 0.51769566, 0.74273174, 0.46173375, 0.63698593,
          0.9206278 ],
         [0.58796342, 0.71476336, 0.16907287, 0.61311718, 0.31318319,
          0.12316385],
         [0.61023826, 0.73298428, 0.64512313, 0.48285432, 0.58613644,
          0.08857069],
         [0.71296366, 0.69024353, 0.10364318, 0.81836811, 0.18747622,
          0.79867537]]],


       [[[0.84509177, 0.04843805, 0.45924854, 0.66491386, 0.07354179,
          0.50894196],
         [0.02303884, 0.62830588, 0.73496715, 0.97180981, 0.96178439,
          0.2374969 ],
         [0.95344329, 0.79215238, 0.34187733, 0.83511901, 0.04164837,
          0.59160107],
         [0.37956115, 0.83265946, 0.29193523, 0.81490331, 0.29666307,
          0.38133984],
         [0.04289927, 0.90272136, 0.37460166, 0.98899718, 0.64508647,
          0.82934657],
         [0.18699918, 0.66854153, 0.9021616 , 0.2385075 , 0.88599241,
          0.33782956]],

        [[0.67034004, 0.73646854, 0.09175239, 0.26982124, 0.28174549,
          0.9985896 ],
         [0.67200059, 0.67909835, 0.05733078, 0.35599393, 0.95902684,
          0.95464241],
         [0.31343219, 0.08617922, 0.19235828, 0.00246891, 0.98110502,
          0.84164381],
         [0.23701314, 0.96539315, 0.30231446, 0.19268657, 0.18193401,
          0.16225955],
         [0.04505666, 0.20369199, 0.11571967, 0.64883506, 0.7791346 ,
          0.19415013],
         [0.26672451, 0.85118467, 0.69524114, 0.46434902, 0.74577984,
          0.48684707]],

        [[0.55732505, 0.77993236, 0.15788989, 0.70161665, 0.24979831,
          0.67232796],
         [0.13414867, 0.86436928, 0.47698469, 0.93773976, 0.46846654,
          0.29164279],
         [0.81977524, 0.42244486, 0.62098696, 0.0256673 , 0.96064018,
          0.46138222],
         [0.77588756, 0.94258501, 0.26644057, 0.6987471 , 0.92208432,
          0.71908334],
         [0.99405773, 0.67200431, 0.89112556, 0.95258474, 0.07292227,
          0.52059923],
         [0.19863222, 0.19096511, 0.30195514, 0.29425999, 0.67650215,
          0.53270304]],

        [[0.38650695, 0.15317459, 0.53713281, 0.14288874, 0.6167232 ,
          0.65723012],
         [0.17604306, 0.59741602, 0.47802721, 0.19335807, 0.01746181,
          0.49931066],
         [0.68606468, 0.3364735 , 0.40813849, 0.36285033, 0.21554295,
          0.78310389],
         [0.91699357, 0.06708089, 0.73887744, 0.66651497, 0.93194772,
          0.19546975],
         [0.31254389, 0.84968813, 0.73915316, 0.82383094, 0.90650928,
          0.65034284],
         [0.06183454, 0.46930783, 0.39784298, 0.37754174, 0.23307457,
          0.13700117]]]])], '\nThe value of eps is:', 1, '\nThe out_type is:', None)

======================================================================
ERROR: test_conv2d_grad_wrt_inputs (test_abstract_conv.TestConv2dGrads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM shape inconsistency:
  bottom shape: 8 1 12 12
  weight shape: 5 1 2 2
  top shape: 8 5 12 12 (expected 8 5 13 13)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1437, in test_conv2d_grad_wrt_inputs
    utt.assert_allclose(f_new(filter_val, out_grad_val), f_old(input_val, filter_val, out_grad_val))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM shape inconsistency:
  bottom shape: 8 1 12 12
  weight shape: 5 1 2 2
  top shape: 8 5 12 12 (expected 8 5 13 13)

Apply node that caused the error: CorrMM_gradInputs{full, (1, 1), (1, 1), 1 False}(Subtensor{::, ::, ::int64, ::int64}.0, <TensorType(float64, 4D)>, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0)
Toposort index: 5
Inputs types: [TensorType(float64, 4D), TensorType(float64, 4D), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(5, 1, 2, 2), (8, 5, 12, 12), (), ()]
Inputs strides: [(32, 32, -16, -8), (5760, 1152, 96, 8), (), ()]
Inputs values: ['not shown', 'not shown', array(12, dtype=int64), array(12, dtype=int64)]
Outputs clients: [['output']]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1432, in test_conv2d_grad_wrt_inputs
    filter_flip=ff

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

======================================================================
ERROR: test_conv2d_grad_wrt_weights (test_abstract_conv.TestConv2dGrads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM shape inconsistency:
  bottom shape: 8 1 12 12
  weight shape: 5 1 2 2
  top shape: 8 5 12 12 (expected 8 5 13 13)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1476, in test_conv2d_grad_wrt_weights
    utt.assert_allclose(f_new(input_val, out_grad_val), f_old(input_val, filter_val, out_grad_val))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: CorrMM shape inconsistency:
  bottom shape: 8 1 12 12
  weight shape: 5 1 2 2
  top shape: 8 5 12 12 (expected 8 5 13 13)

Apply node that caused the error: CorrMM_gradWeights{full, (1, 1), (1, 1), 1 False}(x, <TensorType(float64, 4D)>, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0)
Toposort index: 4
Inputs types: [TensorType(float64, 4D), TensorType(float64, 4D), TensorType(int64, scalar), TensorType(int64, scalar)]
Inputs shapes: [(8, 1, 12, 12), (8, 5, 12, 12), (), ()]
Inputs strides: [(1152, 1152, 96, 8), (5760, 1152, 96, 8), (), ()]
Inputs values: ['not shown', 'not shown', array(2, dtype=int64), array(2, dtype=int64)]
Outputs clients: [[Subtensor{::, ::, ::int64, ::int64}(CorrMM_gradWeights{full, (1, 1), (1, 1), 1 False}.0, Constant{-1}, Constant{-1})]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1473, in test_conv2d_grad_wrt_weights
    filter_flip=ff

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

======================================================================
ERROR: test_fwd (test_abstract_conv.TestUnsharedConv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (3, 2, 4, 1), but the given topgrad has shape (3, 2, 4, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1860, in test_fwd
    utt.verify_grad(unshared_conv_op, [img, kern], mode=self.mode, eps=1)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tests\unittest_tools.py", line 92, in verify_grad
    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gradient.py", line 1780, in verify_grad
    analytic_grad = grad_fn(*[p.copy() for p in pt])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: ('invalid input_shape for gradInputs: the given input_shape would produce an output of shape (3, 2, 4, 1), but the given topgrad has shape (3, 2, 4, 2)\nApply node that caused the error: AbstractConv2d_gradInputs{convdim=2, border_mode=\'full\', subsample=(2, 2), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None, None, None), filter_dilation=(1, 1), num_groups=1, unshared=True}(input 1, Elemwise{mul}.0, Subtensor{int64::}.0)\nToposort index: 9\nInputs types: [TensorType(float64, 6D), TensorType(float64, 4D), TensorType(int64, vector)]\nInputs shapes: [(2, 4, 2, 2, 4, 2), (3, 2, 4, 2), (2,)]\nInputs strides: [(1024, 256, 128, 64, 16, 8), (128, 64, 16, 8), (8,)]\nInputs values: [\'not shown\', \'not shown\', array([4, 2], dtype=int64)]\nOutputs clients: [[\'output\']]\n\nBacktrace when the node is created(use Theano flag traceback.limit=N to make it longer):\n  File "C:\\Users\\mutation\\Desktop\\theano-testcase\\tests\\test_abstract_conv.py", line 1860, in test_fwd\n    utt.verify_grad(unshared_conv_op, [img, kern], mode=self.mode, eps=1)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\tests\\unittest_tools.py", line 92, in verify_grad\n    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1770, in verify_grad\n    disconnected_inputs=\'ignore\')\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 605, in grad\n    grad_dict, wrt, cost_name)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in _populate_grad_dict\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in <listcomp>\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1326, in access_grad_cache\n    term = access_term_cache(node)[idx]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1162, in access_term_cache\n    new_output_grads)\n\nHINT: Use the Theano flag \'exception_verbosity=high\' for a debugprint and storage map footprint of this apply node.', '\nThe error happened with the following inputs:', [array([[[[0.81887369, 0.54734542],
         [0.41671201, 0.74304719],
         [0.36959638, 0.07516654],
         [0.77519298, 0.21940924]],

        [[0.07934213, 0.48678052],
         [0.1536739 , 0.82846513],
         [0.19136857, 0.27040895],
         [0.56103442, 0.90238039]]],


       [[[0.85178834, 0.41808196],
         [0.39347627, 0.01622051],
         [0.29921337, 0.35377822],
         [0.89350267, 0.78613657]],

        [[0.77138693, 0.42005486],
         [0.77602514, 0.46430814],
         [0.18177017, 0.8840256 ],
         [0.71879227, 0.6718813 ]]],


       [[[0.25656363, 0.43080182],
         [0.01645358, 0.23499383],
         [0.51117131, 0.29200924],
         [0.50189351, 0.49827313]],

        [[0.10377152, 0.44644312],
         [0.96918917, 0.73847112],
         [0.71955061, 0.89304339],
         [0.96267468, 0.19705023]]]]), array([[[[[[0.71458996, 0.16192394],
           [0.86625477, 0.62382025],
           [0.95945512, 0.52414204],
           [0.03643288, 0.72687158]],

          [[0.00390984, 0.050294  ],
           [0.99199232, 0.2122575 ],
           [0.94737066, 0.45154055],
           [0.99879467, 0.64750149]]],


         [[[0.70224071, 0.42958177],
           [0.16777476, 0.11813309],
           [0.93788262, 0.91099744],
           [0.39799354, 0.92530327]],

          [[0.74549922, 0.78982636],
           [0.63770852, 0.99274137],
           [0.47610554, 0.10211419],
           [0.87256332, 0.75612704]]]],



        [[[[0.29919884, 0.18625652],
           [0.49435351, 0.0408955 ],
           [0.47835228, 0.3089902 ],
           [0.92058026, 0.91794568]],

          [[0.46848893, 0.23431308],
           [0.08982494, 0.67940357],
           [0.65592832, 0.0039444 ],
           [0.06654134, 0.00112109]]],


         [[[0.66608382, 0.38565116],
           [0.09405827, 0.45856757],
           [0.64434173, 0.59499774],
           [0.79060307, 0.79996907]],

          [[0.67969792, 0.43875185],
           [0.26235889, 0.23652188],
           [0.83900208, 0.36874334],
           [0.61918838, 0.46656433]]]],



        [[[[0.49250063, 0.71862211],
           [0.65415881, 0.9665017 ],
           [0.38957233, 0.97017219],
           [0.36057961, 0.56184234]],

          [[0.03133558, 0.30480028],
           [0.07269465, 0.46721993],
           [0.41345069, 0.42228271],
           [0.79491031, 0.05651855]]],


         [[[0.89718201, 0.31869638],
           [0.36398678, 0.70548804],
           [0.23103497, 0.54827043],
           [0.3195602 , 0.7302113 ]],

          [[0.94257233, 0.77442252],
           [0.86379077, 0.82903615],
           [0.81379647, 0.63166234],
           [0.68810426, 0.09505542]]]],



        [[[[0.87637271, 0.83280508],
           [0.42067349, 0.77582558],
           [0.49097792, 0.52603444],
           [0.71381734, 0.12317237]],

          [[0.45279855, 0.14136043],
           [0.34007602, 0.23354548],
           [0.50744427, 0.42741471],
           [0.53647236, 0.8690842 ]]],


         [[[0.84334885, 0.04136067],
           [0.07753699, 0.36800508],
           [0.74431332, 0.38844287],
           [0.14635092, 0.37732909]],

          [[0.37146278, 0.93263398],
           [0.87870934, 0.63540289],
           [0.07311182, 0.84731036],
           [0.85063229, 0.33730248]]]]],




       [[[[[0.64449643, 0.8330261 ],
           [0.53444522, 0.66108231],
           [0.59079962, 0.408068  ],
           [0.22967834, 0.68915406]],

          [[0.97929665, 0.86124825],
           [0.85470687, 0.55202809],
           [0.42364925, 0.18325788],
           [0.42018606, 0.67910563]]],


         [[[0.32292754, 0.87410072],
           [0.83188017, 0.08145924],
           [0.60184952, 0.86562637],
           [0.71512086, 0.08951758]],

          [[0.95654054, 0.00970529],
           [0.82328371, 0.51948369],
           [0.11782168, 0.52863809],
           [0.67036106, 0.23355256]]]],



        [[[[0.66000613, 0.11651345],
           [0.3830196 , 0.62431415],
           [0.29450684, 0.14830011],
           [0.23563507, 0.56410203]],

          [[0.92096938, 0.72317778],
           [0.95357714, 0.2559986 ],
           [0.64372265, 0.3605287 ],
           [0.42098056, 0.41913791]]],


         [[[0.32387905, 0.82007703],
           [0.49586036, 0.93840594],
           [0.26103986, 0.4649136 ],
           [0.91375817, 0.09912558]],

          [[0.64623778, 0.4209284 ],
           [0.5679438 , 0.8464573 ],
           [0.17137872, 0.64278201],
           [0.05816461, 0.17392473]]]],



        [[[[0.80086056, 0.97524422],
           [0.91764185, 0.93008384],
           [0.89425348, 0.2635315 ],
           [0.49923019, 0.46111572]],

          [[0.28216786, 0.62136171],
           [0.01700001, 0.88253447],
           [0.14659877, 0.40025178],
           [0.61615813, 0.588182  ]]],


         [[[0.05404416, 0.7534885 ],
           [0.54907551, 0.56045366],
           [0.7671055 , 0.21078897],
           [0.9736755 , 0.50771937]],

          [[0.49097889, 0.84919912],
           [0.31654322, 0.79819363],
           [0.20894901, 0.00828292],
           [0.64928251, 0.78287426]]]],



        [[[[0.10600493, 0.43968816],
           [0.09166968, 0.21235807],
           [0.64837616, 0.60179681],
           [0.4684203 , 0.12959741]],

          [[0.24601389, 0.77644581],
           [0.94747335, 0.18831673],
           [0.95207131, 0.97450331],
           [0.59818532, 0.59152573]]],


         [[[0.24403324, 0.33180442],
           [0.43624813, 0.43353388],
           [0.3261148 , 0.0493971 ],
           [0.85964188, 0.79205476]],

          [[0.51894757, 0.2194376 ],
           [0.64761314, 0.81083346],
           [0.37593767, 0.1583613 ],
           [0.74428824, 0.59305375]]]]]])], '\nThe value of eps is:', 1, '\nThe out_type is:', None)

======================================================================
ERROR: test_gradinput (test_abstract_conv.TestUnsharedConv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (3, 2, 4, 1), but the given topgrad has shape (3, 2, 4, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1923, in test_gradinput
    unshared_output = unshared_func(kern, top)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (3, 2, 4, 1), but the given topgrad has shape (3, 2, 4, 2)
Apply node that caused the error: AbstractConv2d_gradInputs{convdim=2, border_mode='full', subsample=(2, 2), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None, None, None), filter_dilation=(1, 1), num_groups=1, unshared=True}(kern, top, TensorConstant{[4 2]})
Toposort index: 0
Inputs types: [TensorType(float64, 6D), TensorType(float64, 4D), TensorType(int32, vector)]
Inputs shapes: [(2, 4, 2, 2, 4, 2), (3, 2, 4, 2), (2,)]
Inputs strides: [(1024, 256, 128, 64, 16, 8), (128, 64, 16, 8), (4,)]
Inputs values: ['not shown', 'not shown', array([4, 2])]
Outputs clients: [['output']]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1919, in test_gradinput
    unshared_out_sym = unshared_conv_op(kern_sym, top_sym, tensor.as_tensor_variable(imshp[-2:]))

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

======================================================================
ERROR: test_gradweight (test_abstract_conv.TestUnsharedConv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: invalid input_shape for gradInputs: the given input_shape would produce an output of shape (3, 2, 4, 1), but the given topgrad has shape (3, 2, 4, 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 1900, in test_gradweight
    utt.verify_grad(conv_gradweight, [img, top], mode=self.mode, eps=1)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tests\unittest_tools.py", line 92, in verify_grad
    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gradient.py", line 1780, in verify_grad
    analytic_grad = grad_fn(*[p.copy() for p in pt])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\abstract_conv.py", line 2954, in perform
    tuple(topgrad.shape)))
ValueError: ('invalid input_shape for gradInputs: the given input_shape would produce an output of shape (3, 2, 4, 1), but the given topgrad has shape (3, 2, 4, 2)\nApply node that caused the error: AbstractConv2d_gradInputs{convdim=2, border_mode=\'full\', subsample=(2, 2), filter_flip=True, imshp=(None, None, None, None), kshp=(None, None, None, None, None, None), filter_dilation=(1, 1), num_groups=1, unshared=True}(Elemwise{mul}.0, input 1, Subtensor{int64::}.0)\nToposort index: 9\nInputs types: [TensorType(float64, 6D), TensorType(float64, 4D), TensorType(int64, vector)]\nInputs shapes: [(2, 4, 2, 2, 4, 2), (3, 2, 4, 2), (2,)]\nInputs strides: [(1024, 256, 128, 64, 16, 8), (128, 64, 16, 8), (8,)]\nInputs values: [\'not shown\', \'not shown\', array([4, 2], dtype=int64)]\nOutputs clients: [[\'output\']]\n\nBacktrace when the node is created(use Theano flag traceback.limit=N to make it longer):\n  File "C:\\Users\\mutation\\Desktop\\theano-testcase\\tests\\test_abstract_conv.py", line 1900, in test_gradweight\n    utt.verify_grad(conv_gradweight, [img, top], mode=self.mode, eps=1)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\tests\\unittest_tools.py", line 92, in verify_grad\n    T.verify_grad(op, pt, n_tests, rng, *args, **kwargs)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1770, in verify_grad\n    disconnected_inputs=\'ignore\')\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 605, in grad\n    grad_dict, wrt, cost_name)\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in _populate_grad_dict\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1371, in <listcomp>\n    rval = [access_grad_cache(elem) for elem in wrt]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1326, in access_grad_cache\n    term = access_term_cache(node)[idx]\n  File "C:\\ProgramData\\Anaconda3\\envs\\keras\\lib\\site-packages\\theano\\gradient.py", line 1162, in access_term_cache\n    new_output_grads)\n\nHINT: Use the Theano flag \'exception_verbosity=high\' for a debugprint and storage map footprint of this apply node.', '\nThe error happened with the following inputs:', [array([[[[0.05404416, 0.7534885 ],
         [0.54907551, 0.56045366],
         [0.7671055 , 0.21078897],
         [0.9736755 , 0.50771937]],

        [[0.49097889, 0.84919912],
         [0.31654322, 0.79819363],
         [0.20894901, 0.00828292],
         [0.64928251, 0.78287426]]],


       [[[0.10600493, 0.43968816],
         [0.09166968, 0.21235807],
         [0.64837616, 0.60179681],
         [0.4684203 , 0.12959741]],

        [[0.24601389, 0.77644581],
         [0.94747335, 0.18831673],
         [0.95207131, 0.97450331],
         [0.59818532, 0.59152573]]],


       [[[0.24403324, 0.33180442],
         [0.43624813, 0.43353388],
         [0.3261148 , 0.0493971 ],
         [0.85964188, 0.79205476]],

        [[0.51894757, 0.2194376 ],
         [0.64761314, 0.81083346],
         [0.37593767, 0.1583613 ],
         [0.74428824, 0.59305375]]]]), array([[[[0.10850424, 0.2295715 ],
         [0.41988769, 0.93801504],
         [0.68364089, 0.04064517],
         [0.16947985, 0.51999844]],

        [[0.7675624 , 0.25592513],
         [0.48114321, 0.10097116],
         [0.95411734, 0.02911458],
         [0.72241687, 0.50596048]]],


       [[[0.67985301, 0.03671169],
         [0.15567476, 0.13844643],
         [0.0458779 , 0.92677609],
         [0.15817435, 0.23479392]],

        [[0.21824616, 0.49834023],
         [0.86638214, 0.3872798 ],
         [0.06933087, 0.05724104],
         [0.03622071, 0.57086973]]],


       [[[0.4123434 , 0.35410939],
         [0.44043732, 0.23750906],
         [0.2956896 , 0.15874069],
         [0.68651944, 0.85427246]],

        [[0.70742547, 0.56301974],
         [0.33653441, 0.91111082],
         [0.65449806, 0.20102082],
         [0.20599207, 0.41088069]]]])], '\nThe value of eps is:', 1, '\nThe out_type is:', None)

======================================================================
FAIL: test_get_shape (test_abstract_conv.TestConvGradInputsShape)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 189, in test_get_shape
    self.assertEqual(computed_image_shape, image_shape)
AssertionError: Tuples differ: (59, 61, 0, 0) != (59, 61, 1, 1)

First differing element 2:
0
1

- (59, 61, 0, 0)
?          ^  ^

+ (59, 61, 1, 1)
?          ^  ^


======================================================================
FAIL: test_basic (test_abstract_conv.TestGetConvOutShape)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 119, in test_basic
    self.assertTrue(test4_params == (3, 4, 6, 4))
AssertionError: False is not true

======================================================================
FAIL: test_basic_3d (test_abstract_conv.TestGetConvOutShape)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_abstract_conv.py", line 137, in test_basic_3d
    self.assertTrue(test4_params == (3, 4, 6, 4, 10))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 39 tests in 61.493s

FAILED (failures=3, errors=8)
