ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

.EERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, vector)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, vector)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, vector)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, vector)>)

......ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', v)

...ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', x)

....ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', m.T)

.......s......ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, vector)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, vector)>)

.ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

..ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

....ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', v)

.ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', s)

.ERROR (theano.gof.opt): SeqOptimizer apply <theano.tensor.opt.ShapeOptimizer object at 0x000001EF71778B38>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 251, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\opt.py", line 93, in optimize
    self.add_requirements(fgraph)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1488, in add_requirements
    fgraph.attach_feature(ShapeFeature())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 546, in attach_feature
    attach(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1305, in on_attach
    self.on_import(fgraph, node, reason='on_attach')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, vector)>)

...
======================================================================
ERROR: test_borrow_output (__main__.T_function)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_function_module.py", line 514, in test_borrow_output
    f = function([a], Out(a, borrow=False))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1839, in orig_function
    name=name)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1526, in __init__
    insert_deepcopy(fgraph, inputs, outputs + additional_outputs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1169, in insert_deepcopy
    reason="insert_deepcopy")
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 445, in change_input
    self.__import_r__(new_r, reason=reason)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 346, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 409, in __import__
    self.execute_callbacks('on_import', node, reason)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\fg.py", line 594, in execute_callbacks
    fn(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1322, in on_import
    self.init_r(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1276, in init_r
    self.set_shape(r, self.shape_tuple(r))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in shape_tuple
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1031, in <listcomp>
    return tuple([self.shape_ir(i, r) for i in xrange(r.ndim)])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\opt.py", line 1019, in shape_ir
    s = Shape_i(i)(r)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\ops.py", line 369, in make_node
    raise TypeError('x must be Variable with ndim attribute', x)
TypeError: ('x must be Variable with ndim attribute', <TensorType(float64, matrix)>)

----------------------------------------------------------------------
Ran 41 tests in 5.749s

FAILED (errors=1, skipped=1)
