2020-10-05 21:22:15.826919: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Running tests under Python 3.6.12: C:\ProgramData\Anaconda3\envs\keras\python.exe
[ RUN      ] AbcTest.testAbstract
[       OK ] AbcTest.testAbstract
[ RUN      ] AbcTest.testConcrete
[       OK ] AbcTest.testConcrete
[ RUN      ] AbcTest.test_session
[  SKIPPED ] AbcTest.test_session
[ RUN      ] FlattenTest.test_attribute_traversal_key
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W1005 21:22:19.543996  7816 deprecation.py:506] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
[  FAILED  ] FlattenTest.test_attribute_traversal_key
[ RUN      ] FlattenTest.test_attributes_to_ignore
[  FAILED  ] FlattenTest.test_attributes_to_ignore
[ RUN      ] FlattenTest.test_flatten0 (<function FlattenTest.<lambda> at 0x0000024EC1F63730>)
[  FAILED  ] FlattenTest.test_flatten0 (<function FlattenTest.<lambda> at 0x0000024EC1F63730>)
[ RUN      ] FlattenTest.test_flatten1 (<class 'list'>)
[  FAILED  ] FlattenTest.test_flatten1 (<class 'list'>)
[ RUN      ] FlattenTest.test_flatten2 (<class 'tuple'>)
[  FAILED  ] FlattenTest.test_flatten2 (<class 'tuple'>)
[ RUN      ] FlattenTest.test_flatten3 (<function <lambda> at 0x0000024EC1F58EA0>)
[  FAILED  ] FlattenTest.test_flatten3 (<function <lambda> at 0x0000024EC1F58EA0>)
[ RUN      ] FlattenTest.test_model_discover_submodule
[  FAILED  ] FlattenTest.test_model_discover_submodule
[ RUN      ] FlattenTest.test_module_discover_layer_variable
[  FAILED  ] FlattenTest.test_module_discover_layer_variable
[ RUN      ] FlattenTest.test_session
[  SKIPPED ] FlattenTest.test_session
[ RUN      ] FlattenTest.test_with_path
[  FAILED  ] FlattenTest.test_with_path
[ RUN      ] ForwardMethodsTest.testEntersNameScope_call
2020-10-05 21:22:19.596336: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-05 21:22:19.709568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:22:19.710097: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:22:19.713505: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:22:19.716864: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:22:19.718481: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:22:19.723231: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:22:19.726445: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:22:19.735770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:22:19.736703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:22:19.737427: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-05 21:22:19.751126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:22:19.751796: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:22:19.752139: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:22:19.752478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:22:19.752818: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:22:19.753164: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:22:19.753510: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:22:19.753856: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:22:19.754665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:22:20.678754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:22:20.679173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:22:20.679411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:22:20.680158: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W1005 21:22:20.700047  7816 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2020-10-05 21:22:20.710505: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:22:20.711025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:22:20.711371: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:22:20.711713: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:22:20.712050: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:22:20.712392: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:22:20.712737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:22:20.713088: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:22:20.713687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:22:20.713994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:22:20.714405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:22:20.714624: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:22:20.715116: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ForwardMethodsTest.testEntersNameScope_call
[ RUN      ] ForwardMethodsTest.testEntersNameScope_concreteFunction
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x0000024EC2001C80> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
W1005 21:22:22.418462  7816 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x0000024EC2001C80> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
2020-10-05 21:22:22.430202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:22:22.430732: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:22:22.431080: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:22:22.431426: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:22:22.431767: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:22:22.432109: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:22:22.432461: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:22:22.432814: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:22:22.433372: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:22:22.433684: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:22:22.434034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:22:22.434260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:22:22.434749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000002511FF4C378> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
W1005 21:22:22.543437  7816 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000002511FF4C378> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
[       OK ] ForwardMethodsTest.testEntersNameScope_concreteFunction
[ RUN      ] ForwardMethodsTest.testFunctionType
[       OK ] ForwardMethodsTest.testFunctionType
[ RUN      ] ForwardMethodsTest.test_session
[  SKIPPED ] ForwardMethodsTest.test_session
[ RUN      ] ModuleTrackingTest.test_non_ctor_submodule
[  FAILED  ] ModuleTrackingTest.test_non_ctor_submodule
[ RUN      ] ModuleTrackingTest.test_session
[  SKIPPED ] ModuleTrackingTest.test_session
[ RUN      ] ModuleTrackingTest.test_submodules
[  FAILED  ] ModuleTrackingTest.test_submodules
[ RUN      ] NameScopeTest.test_memoized_in_tf2
[  SKIPPED ] NameScopeTest.test_memoized_in_tf2
[ RUN      ] NameScopeTest.test_not_memoized_in_tf1
[       OK ] NameScopeTest.test_not_memoized_in_tf1
[ RUN      ] NameScopeTest.test_session
[  SKIPPED ] NameScopeTest.test_session
[ RUN      ] TestModuleNaming.test_construct_in_scope
[       OK ] TestModuleNaming.test_construct_in_scope
[ RUN      ] TestModuleNaming.test_ctor_error_closes_name_scope
[       OK ] TestModuleNaming.test_ctor_error_closes_name_scope
[ RUN      ] TestModuleNaming.test_ctor_error_handles_ctor_not_opening_name_scope
[       OK ] TestModuleNaming.test_ctor_error_handles_ctor_not_opening_name_scope
[ RUN      ] TestModuleNaming.test_does_not_evaluate_property_methods
[       OK ] TestModuleNaming.test_does_not_evaluate_property_methods
[ RUN      ] TestModuleNaming.test_enters_name_scope_in_call
[       OK ] TestModuleNaming.test_enters_name_scope_in_call
[ RUN      ] TestModuleNaming.test_enters_name_scope_in_other_method
[       OK ] TestModuleNaming.test_enters_name_scope_in_other_method
[ RUN      ] TestModuleNaming.test_forward_method_closes_name_scope
[       OK ] TestModuleNaming.test_forward_method_closes_name_scope
[ RUN      ] TestModuleNaming.test_get_attr_doesnt_enter_name_scope
[       OK ] TestModuleNaming.test_get_attr_doesnt_enter_name_scope
[ RUN      ] TestModuleNaming.test_get_attribute_doesnt_enter_name_scope
[       OK ] TestModuleNaming.test_get_attribute_doesnt_enter_name_scope
[ RUN      ] TestModuleNaming.test_invalid_name
[       OK ] TestModuleNaming.test_invalid_name
[ RUN      ] TestModuleNaming.test_module_numbering_in_graph
2020-10-05 21:22:22.595075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:22:22.595809: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:22:22.596307: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:22:22.596791: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:22:22.597274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:22:22.597757: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:22:22.598246: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:22:22.598735: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:22:22.599512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:22:22.599944: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:22:22.600450: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:22:22.600762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:22:22.601406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  SKIPPED ] TestModuleNaming.test_module_numbering_in_graph
[ RUN      ] TestModuleNaming.test_modules_not_numbered_in_eager
2020-10-05 21:22:22.613694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:22:22.614201: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:22:22.614541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:22:22.614880: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:22:22.615264: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:22:22.615631: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:22:22.616001: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:22:22.616361: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:22:22.616906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:22:22.617205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:22:22.617553: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:22:22.617771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:22:22.618292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] TestModuleNaming.test_modules_not_numbered_in_eager
[ RUN      ] TestModuleNaming.test_overridden_name_scope
[       OK ] TestModuleNaming.test_overridden_name_scope
[ RUN      ] TestModuleNaming.test_patched_callable
[       OK ] TestModuleNaming.test_patched_callable
[ RUN      ] TestModuleNaming.test_property
[       OK ] TestModuleNaming.test_property
[ RUN      ] TestModuleNaming.test_property_no_name_scope
[       OK ] TestModuleNaming.test_property_no_name_scope
[ RUN      ] TestModuleNaming.test_session
[  SKIPPED ] TestModuleNaming.test_session
[ RUN      ] TestModuleNaming.test_single_name
[       OK ] TestModuleNaming.test_single_name
[ RUN      ] TestModuleNaming.test_subclassed_module
[       OK ] TestModuleNaming.test_subclassed_module
[ RUN      ] TestModuleNaming.test_submodule_created_late
[       OK ] TestModuleNaming.test_submodule_created_late
[ RUN      ] VariableNamingTest.test_session
[  SKIPPED ] VariableNamingTest.test_session
[ RUN      ] VariableNamingTest.test_variable_names
[       OK ] VariableNamingTest.test_variable_names
[ RUN      ] VariableTrackingTest.test_session
[  SKIPPED ] VariableTrackingTest.test_session
[ RUN      ] VariableTrackingTest.test_supports_distributed_variables
[  FAILED  ] VariableTrackingTest.test_supports_distributed_variables
[ RUN      ] VariableTrackingTest.test_trainable_variables
[  FAILED  ] VariableTrackingTest.test_trainable_variables
[ RUN      ] VariableTrackingTest.test_trainable_variables_ignores_non_trainable
[  FAILED  ] VariableTrackingTest.test_trainable_variables_ignores_non_trainable
[ RUN      ] VariableTrackingTest.test_variables
[  FAILED  ] VariableTrackingTest.test_variables
======================================================================
ERROR: test_attribute_traversal_key (__main__.FlattenTest)
FlattenTest.test_attribute_traversal_key
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 952, in test_attribute_traversal_key
    mod.variables,
  File "module_test.py", line 1128, in variables
    attribute_traversal_key=key_function))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_attributes_to_ignore (__main__.FlattenTest)
FlattenTest.test_attributes_to_ignore
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 982, in test_attributes_to_ignore
    self.assertEmpty(mod.submodules)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 193, in submodules
    return tuple(self._flatten(predicate=_is_module))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_flatten0 (<function FlattenTest.<lambda> at 0x0000024EC1F63730>) (__main__.FlattenTest)
FlattenTest.test_flatten0 (<function FlattenTest.<lambda> at 0x0000024EC1F63730>)
test_flatten(<function FlattenTest.<lambda> at 0x0000024EC1F63730>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\absl\testing\parameterized.py", line 286, in bound_param_test
    return test_method(self, testcase_params)
  File "module_test.py", line 932, in test_flatten
    list(parent._flatten(recursive=False, predicate=is_member)),
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_flatten1 (<class 'list'>) (__main__.FlattenTest)
FlattenTest.test_flatten1 (<class 'list'>)
test_flatten(<class 'list'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\absl\testing\parameterized.py", line 286, in bound_param_test
    return test_method(self, testcase_params)
  File "module_test.py", line 932, in test_flatten
    list(parent._flatten(recursive=False, predicate=is_member)),
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_flatten2 (<class 'tuple'>) (__main__.FlattenTest)
FlattenTest.test_flatten2 (<class 'tuple'>)
test_flatten(<class 'tuple'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\absl\testing\parameterized.py", line 286, in bound_param_test
    return test_method(self, testcase_params)
  File "module_test.py", line 932, in test_flatten
    list(parent._flatten(recursive=False, predicate=is_member)),
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_flatten3 (<function <lambda> at 0x0000024EC1F58EA0>) (__main__.FlattenTest)
FlattenTest.test_flatten3 (<function <lambda> at 0x0000024EC1F58EA0>)
test_flatten(<function <lambda> at 0x0000024EC1F58EA0>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\absl\testing\parameterized.py", line 286, in bound_param_test
    return test_method(self, testcase_params)
  File "module_test.py", line 932, in test_flatten
    list(parent._flatten(recursive=False, predicate=is_member)),
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_model_discover_submodule (__main__.FlattenTest)
FlattenTest.test_model_discover_submodule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 1072, in test_model_discover_submodule
    self.assertEqual(m.submodules, (m.layers[0], m.layers[1]))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 193, in submodules
    return tuple(self._flatten(predicate=_is_module))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_module_discover_layer_variable (__main__.FlattenTest)
FlattenTest.test_module_discover_layer_variable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 1036, in test_module_discover_layer_variable
    self.assertEmpty(m.variables)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 155, in variables
    return tuple(self._flatten(predicate=_is_variable))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_with_path (__main__.FlattenTest)
FlattenTest.test_with_path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 1006, in test_with_path
    mod._flatten(with_path=True, predicate=module._is_variable))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_non_ctor_submodule (__main__.ModuleTrackingTest)
ModuleTrackingTest.test_non_ctor_submodule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 560, in test_non_ctor_submodule
    self.assertEqual(set(m.submodules), {leaf1})
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 193, in submodules
    return tuple(self._flatten(predicate=_is_module))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_submodules (__main__.ModuleTrackingTest)
ModuleTrackingTest.test_submodules
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 546, in test_submodules
    self.assertEqual(list(m.submodules), [m.child, m.child.child])
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 193, in submodules
    return tuple(self._flatten(predicate=_is_module))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_supports_distributed_variables (__main__.VariableTrackingTest)
VariableTrackingTest.test_supports_distributed_variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 532, in test_supports_distributed_variables
    self.assertEqual(m.variables, (mirrored, tpu, aggregating))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 155, in variables
    return tuple(self._flatten(predicate=_is_variable))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_trainable_variables (__main__.VariableTrackingTest)
VariableTrackingTest.test_trainable_variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 474, in test_trainable_variables
    self.assertEqual(m.trainable_variables,
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 170, in trainable_variables
    return tuple(self._flatten(predicate=_is_trainable_variable))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_trainable_variables_ignores_non_trainable (__main__.VariableTrackingTest)
VariableTrackingTest.test_trainable_variables_ignores_non_trainable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 490, in test_trainable_variables_ignores_non_trainable
    self.assertEqual(len(m.trainable_variables), 0)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 170, in trainable_variables
    return tuple(self._flatten(predicate=_is_trainable_variable))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

======================================================================
ERROR: test_variables (__main__.VariableTrackingTest)
VariableTrackingTest.test_variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 462, in test_variables
    self.assertEqual(m.variables, (m.w, m.child.w, m.child.child.w))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 155, in variables
    return tuple(self._flatten(predicate=_is_variable))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\module\module.py", line 340, in _flatten_module
    leaf_path = (key,) - leaf_path
TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

----------------------------------------------------------------------
Ran 50 tests in 3.140s

FAILED (errors=15, skipped=10)
