2020-10-06 19:15:20.285966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Running tests under Python 3.6.12: C:\ProgramData\Anaconda3\envs\keras\python.exe
[ RUN      ] QueueRunnerTest.testBasic
2020-10-06 19:15:24.123862: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-06 19:15:24.242902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:24.246074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:24.252739: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:24.256103: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:24.257753: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:24.262661: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:24.265882: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:24.275179: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:24.276135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:24.276803: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-06 19:15:24.290825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:24.291370: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:24.291714: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:24.292053: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:24.292394: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:24.292733: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:24.293075: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:24.293458: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:24.294336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.233973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.234365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.234583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.235396: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:From queue_runner_test.py:102: RefVariable.count_up_to (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Dataset.range instead.
W1006 19:15:25.246136 18828 deprecation.py:323] From queue_runner_test.py:102: RefVariable.count_up_to (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Dataset.range instead.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\variables.py:2522: count_up_to (from tensorflow.python.ops.state_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Dataset.range instead.
W1006 19:15:25.246136 18828 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\variables.py:2522: count_up_to (from tensorflow.python.ops.state_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Dataset.range instead.
WARNING:tensorflow:From queue_runner_test.py:108: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1006 19:15:25.261717 18828 deprecation.py:323] From queue_runner_test.py:108: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
[       OK ] QueueRunnerTest.testBasic
[ RUN      ] QueueRunnerTest.testExceptionsCaptured
2020-10-06 19:15:25.281350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.282317: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.282963: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.283616: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.284248: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.284882: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.285524: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.286168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.287092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.287469: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.287906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.288185: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.288769: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'i fail' cannot be interpreted as a Tensor. ("The name 'i fail' refers to an Operation not in the graph.")
E1006 19:15:25.293002 21980 queue_runner_impl.py:275] Exception in QueueRunner: Fetch argument 'i fail' cannot be interpreted as a Tensor. ("The name 'i fail' refers to an Operation not in the graph.")
ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'so fail' cannot be interpreted as a Tensor. ("The name 'so fail' refers to an Operation not in the graph.")
E1006 19:15:25.293002  8972 queue_runner_impl.py:275] Exception in QueueRunner: Fetch argument 'so fail' cannot be interpreted as a Tensor. ("The name 'so fail' refers to an Operation not in the graph.")
Exception in thread QueueRunnerThread-fifo_queue-i fail:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 305, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3667, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'i fail' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 252, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 1244, in make_callable
    object_identity.ObjectIdentityDictionary())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 266, in for_fetch
    return _ListFetchMapper(fetch)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 276, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 315, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'i fail' cannot be interpreted as a Tensor. ("The name 'i fail' refers to an Operation not in the graph.")

Exception in thread QueueRunnerThread-fifo_queue-so fail:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 305, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3667, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'so fail' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 252, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 1244, in make_callable
    object_identity.ObjectIdentityDictionary())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 266, in for_fetch
    return _ListFetchMapper(fetch)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 276, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 315, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'so fail' cannot be interpreted as a Tensor. ("The name 'so fail' refers to an Operation not in the graph.")

[       OK ] QueueRunnerTest.testExceptionsCaptured
[ RUN      ] QueueRunnerTest.testGracePeriod
2020-10-06 19:15:25.315776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.316400: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.316756: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.317098: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.317451: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.317812: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.318169: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.318529: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.319101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.319415: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.319776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.320001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.320493: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] QueueRunnerTest.testGracePeriod
[ RUN      ] QueueRunnerTest.testIgnoreMultiStarts
2020-10-06 19:15:25.363431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.365408: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.366689: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.368080: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.369352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.370624: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.371939: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.373234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.375195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.376306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.377602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.378328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.380101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] QueueRunnerTest.testIgnoreMultiStarts
[ RUN      ] QueueRunnerTest.testMultipleSessions
2020-10-06 19:15:25.405973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.407950: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.409222: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.410494: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.411757: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.413046: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.414333: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.415619: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.417527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.418268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.419140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.419686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.420781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
2020-10-06 19:15:25.423297: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.424561: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.425419: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.426267: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.427119: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.427842: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.428334: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.428825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.429602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.430026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.430533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.430846: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.431537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] QueueRunnerTest.testMultipleSessions
[ RUN      ] QueueRunnerTest.testName
WARNING:tensorflow:From queue_runner_test.py:498: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1006 19:15:25.437193 18828 deprecation.py:323] From queue_runner_test.py:498: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
[       OK ] QueueRunnerTest.testName
[ RUN      ] QueueRunnerTest.testQueueRunnerSerializationRoundTrip
[       OK ] QueueRunnerTest.testQueueRunnerSerializationRoundTrip
[ RUN      ] QueueRunnerTest.testRealDequeueEnqueue
2020-10-06 19:15:25.446487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.447004: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.447346: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.447691: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.448042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.448387: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.448734: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.449081: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.449643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.449942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.450292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.450510: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.451058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] QueueRunnerTest.testRealDequeueEnqueue
[ RUN      ] QueueRunnerTest.testRequestStopOnException
2020-10-06 19:15:25.536074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.536782: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.537254: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.537724: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.538193: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.538662: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.539054: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.539398: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.539957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.540262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.540612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.540831: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.541315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
INFO:tensorflow:Error reported to Coordinator: <class 'ValueError'>, Fetch argument 'not an op' cannot be interpreted as a Tensor. ("The name 'not an op' refers to an Operation not in the graph.")
I1006 19:15:25.530926  7060 coordinator.py:224] Error reported to Coordinator: <class 'ValueError'>, Fetch argument 'not an op' cannot be interpreted as a Tensor. ("The name 'not an op' refers to an Operation not in the graph.")
[       OK ] QueueRunnerTest.testRequestStopOnException
[ RUN      ] QueueRunnerTest.testRespectCoordShouldStop
2020-10-06 19:15:25.563832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.565219: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.566171: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.567125: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.568067: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.569010: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.569751: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.570467: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.571543: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.572140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.572849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.573285: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.574175: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] QueueRunnerTest.testRespectCoordShouldStop
[ RUN      ] QueueRunnerTest.testStartQueueRunners
2020-10-06 19:15:25.613281: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:25.615211: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:25.616509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:25.617797: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:25.619074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:25.620048: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:25.620997: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:25.621944: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:25.623440: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:25.624258: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:25.625223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:25.625821: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:25.627047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:From queue_runner_test.py:528: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W1006 19:15:26.046447 18828 deprecation.py:323] From queue_runner_test.py:528: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
[  FAILED  ] QueueRunnerTest.testStartQueueRunners
[ RUN      ] QueueRunnerTest.testStartQueueRunnersIgnoresMonitoredSession
2020-10-06 19:15:26.072361: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:26.074073: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:26.075221: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:26.076366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:26.077497: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:26.078753: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:26.079918: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:26.081085: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:26.082445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:26.083089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:26.083844: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:26.084315: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:26.085282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W1006 19:15:26.108936 18828 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
I1006 19:15:26.140178 18828 monitored_session.py:240] Graph was finalized.
2020-10-06 19:15:26.143894: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:26.144456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:26.144829: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:26.145200: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:26.145579: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:26.145995: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:26.146429: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:26.146872: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:26.147444: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:26.147789: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:26.148168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:26.148406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:26.148934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
INFO:tensorflow:Running local_init_op.
I1006 19:15:26.155796 18828 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I1006 19:15:26.155796 18828 session_manager.py:502] Done running local_init_op.
[  FAILED  ] QueueRunnerTest.testStartQueueRunnersIgnoresMonitoredSession
[ RUN      ] QueueRunnerTest.testStartQueueRunnersNonDefaultGraph
2020-10-06 19:15:26.191535: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:26.193137: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:26.194161: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:26.195180: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:26.196198: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:26.197219: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:26.198249: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:26.199277: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:26.200832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:26.201724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:26.202457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:26.202847: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:26.203641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] QueueRunnerTest.testStartQueueRunnersNonDefaultGraph
[ RUN      ] QueueRunnerTest.testStartQueueRunnersRaisesIfNotASession
2020-10-06 19:15:26.216975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:26.217573: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:26.217940: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:26.218300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:26.218659: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:26.219015: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:26.219372: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:26.219734: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:26.220337: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:26.220663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:26.221040: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:26.221283: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:26.221813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  FAILED  ] QueueRunnerTest.testStartQueueRunnersRaisesIfNotASession
[ RUN      ] QueueRunnerTest.testThreads
2020-10-06 19:15:26.226514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:26.227026: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:26.227372: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:26.227719: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:26.228060: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:26.228402: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:26.228745: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:26.229088: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:26.229643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:26.229941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:26.230298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:26.230518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:26.230989: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")
E1006 19:15:26.233910 14628 queue_runner_impl.py:275] Exception in QueueRunner: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")
Exception in thread QueueRunnerThread-fifo_queue-bad_op:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 305, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3667, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'bad_op' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 252, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 1244, in make_callable
    object_identity.ObjectIdentityDictionary())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 266, in for_fetch
    return _ListFetchMapper(fetch)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 276, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 315, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")

ERROR:tensorflow:Exception in QueueRunner: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")
E1006 19:15:26.249529  6872 queue_runner_impl.py:275] Exception in QueueRunner: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")
Exception in thread QueueRunnerThread-fifo_queue-bad_op:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 305, in __init__
    fetch, allow_tensor=True, allow_operation=True))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3667, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'bad_op' refers to an Operation not in the graph."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 252, in _run
    enqueue_callable = sess.make_callable(enqueue_op)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 1244, in make_callable
    object_identity.ObjectIdentityDictionary())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 474, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 266, in for_fetch
    return _ListFetchMapper(fetch)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 375, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 276, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\client\session.py", line 315, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument 'bad_op' cannot be interpreted as a Tensor. ("The name 'bad_op' refers to an Operation not in the graph.")

[       OK ] QueueRunnerTest.testThreads
[ RUN      ] QueueRunnerTest.testTwoOps
2020-10-06 19:15:26.252897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 19:15:26.253424: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 19:15:26.253784: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 19:15:26.254124: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 19:15:26.254470: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 19:15:26.254812: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 19:15:26.255160: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 19:15:26.255503: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 19:15:26.256052: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 19:15:26.256353: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 19:15:26.256702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 19:15:26.256920: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 19:15:26.257390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] QueueRunnerTest.testTwoOps
[ RUN      ] QueueRunnerTest.test_session
[  SKIPPED ] QueueRunnerTest.test_session
======================================================================
ERROR: testStartQueueRunners (__main__.QueueRunnerTest)
QueueRunnerTest.testStartQueueRunners
----------------------------------------------------------------------
Traceback (most recent call last):
  File "queue_runner_test.py", line 528, in testStartQueueRunners
    threads = queue_runner_impl.start_queue_runners(sess)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 466, in start_queue_runners
    "Given class: {}".format(sess.__class__))
TypeError: sess must be a `tf.Session` object. Given class: <class 'tensorflow.python.framework.test_util.ErrorLoggingSession'>

======================================================================
ERROR: testStartQueueRunnersIgnoresMonitoredSession (__main__.QueueRunnerTest)
QueueRunnerTest.testStartQueueRunnersIgnoresMonitoredSession
----------------------------------------------------------------------
Traceback (most recent call last):
  File "queue_runner_test.py", line 590, in testStartQueueRunnersIgnoresMonitoredSession
    monitored_session.MonitoredSession())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1014, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 725, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1207, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 1212, in _create_session
    return self._sess_creator.create_session()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\monitored_session.py", line 882, in create_session
    queue_runner.start_queue_runners(sess=self.tf_sess, coord=self.coord)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 466, in start_queue_runners
    "Given class: {}".format(sess.__class__))
TypeError: sess must be a `tf.Session` object. Given class: <class 'tensorflow.python.client.session.Session'>

======================================================================
ERROR: testStartQueueRunnersNonDefaultGraph (__main__.QueueRunnerTest)
QueueRunnerTest.testStartQueueRunnersNonDefaultGraph
----------------------------------------------------------------------
Traceback (most recent call last):
  File "queue_runner_test.py", line 622, in testStartQueueRunnersNonDefaultGraph
    threads = queue_runner_impl.start_queue_runners(sess)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 466, in start_queue_runners
    "Given class: {}".format(sess.__class__))
TypeError: sess must be a `tf.Session` object. Given class: <class 'tensorflow.python.framework.test_util.ErrorLoggingSession'>

======================================================================
ERROR: testStartQueueRunnersRaisesIfNotASession (__main__.QueueRunnerTest)
QueueRunnerTest.testStartQueueRunnersRaisesIfNotASession
----------------------------------------------------------------------
Traceback (most recent call last):
  File "queue_runner_test.py", line 564, in testStartQueueRunnersRaisesIfNotASession
    queue_runner_impl.start_queue_runners("NotASession")
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\training\queue_runner_impl.py", line 475, in start_queue_runners
    with sess.graph.as_default():
AttributeError: 'str' object has no attribute 'graph'

----------------------------------------------------------------------
Ran 17 tests in 2.175s

FAILED (errors=4, skipped=1)
