EEEEEE....EEEEEEEEEEEEE.EEEE...EEE
======================================================================
ERROR: test_fwd (theano.tensor.nnet.tests.test_abstract_conv.Grouped_conv_noOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1536, in test_fwd
    mode=self.ref_mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(img, Subtensor{::, ::, ::int64, ::int64}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradinputs (theano.tensor.nnet.tests.test_abstract_conv.Grouped_conv_noOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1630, in test_gradinputs
    mode=self.ref_mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradInputs{valid, (1, 1), (1, 1), 1 False}(Subtensor{::, ::, ::int64, ::int64}.0, top, TensorConstant{5}, TensorConstant{5}), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradweights (theano.tensor.nnet.tests.test_abstract_conv.Grouped_conv_noOptim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1581, in test_gradweights
    mode=self.ref_mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradWeights{valid, (1, 1), (1, 1), 1 False}(img, kern, TensorConstant{3}, TensorConstant{3}), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_fwd (test_corr.TestAsymmetricCorr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1977, in test_fwd
    asymmetric_func = theano.function([img_sym, kern_sym], asymmetric_out_sym, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{((1, 2), (2, 1)), (1, 1), (1, 1), 1 False}(img, Subtensor{::, ::, ::int64, ::int64}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradinput (test_corr.TestAsymmetricCorr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 2053, in test_gradinput
    asymmetric_func = theano.function([kern_sym, top_sym], asymmetric_out_sym, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradInputs{((1, 2), (2, 1)), (1, 1), (1, 1), 1 False}(Subtensor{::, ::, ::int64, ::int64}.0, top, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradweight (test_corr.TestAsymmetricCorr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 2014, in test_gradweight
    asymmetric_func = theano.function([img_sym, top_sym], asymmetric_out_sym, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradWeights{((1, 2), (2, 1)), (1, 1), (1, 1), 1 False}(img, top, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_interface (test_corr.TestCausalCorr)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 2098, in test_interface
    causal_func = theano.function([img_sym, kern_sym], sym_out, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{((4, 0), (0, 0)), (1, 1), (2, 1), 1 False}(InplaceDimShuffle{0,1,2,x}.0, Subtensor{::, ::, ::int64, ::int64}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_basic (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 159, in test_basic
    self.validate(img, fil, border_mode, verify_grad=False)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_dtype_upcast (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 282, in test_dtype_upcast
    f = theano.function([a_tens, b_tens], c_tens, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(<TensorType(float32, 4D)>, <TensorType(float32, 4D)>), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_filter_dilation (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 196, in test_filter_dilation
    self.validate((3, 2, 7, 5), (5, 2, 2, 3), 'valid', filter_dilation=(2, 2))
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (2, 2), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_full_mode (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 242, in test_full_mode
    self.validate((3, 2, 5, 5), (4, 2, 8, 8), 'full')
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{full, (1, 1), (1, 1), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_img_kernel_same_shape (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 165, in test_img_kernel_same_shape
    self.validate((3, 2, 3, 3), (4, 2, 3, 3), 'full')
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{full, (1, 1), (1, 1), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_infer_shape_forward (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 316, in test_infer_shape_forward
    warn=False)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tests\unittest_tools.py", line 260, in _compile_and_check
    outputs_function = theano.function(inputs, outputs, mode=mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(<TensorType(float64, 4D)>, <TensorType(float64, 4D)>), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_infer_shape_gradI (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 387, in test_infer_shape_gradI
    f = theano.function([adtens, bdtens], cdtens)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(<TensorType(float64, 4D)>, <TensorType(float64, 4D)>), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_infer_shape_gradW (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 347, in test_infer_shape_gradW
    f = theano.function([adtens, bdtens], cdtens)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(<TensorType(float64, 4D)>, <TensorType(float64, 4D)>), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_invalid_filter_shape (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 236, in test_invalid_filter_shape
    'valid')
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 733, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\unittest\case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_non_contiguous (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 399, in test_non_contiguous
    self.validate((2, 2, 3, 3), (2, 2, 2, 2), 'valid', non_contiguous=True)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_shape_Constant_tensor (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 223, in test_shape_Constant_tensor
    (5, 2, 2, 3), border_mode)
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_subsample (test_corr.TestCorr2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 175, in test_subsample
    self.validate((3, 2, 7, 5), (5, 2, 2, 3), 'valid', subsample=(2, 2))
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 68, in validate
    theano_corr = theano.function([input, filters], output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (2, 2), (1, 1), 1 False}(input, filters), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_fwd (test_corr.TestGroupCorr2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1525, in test_fwd
    grouped_func = theano.function([img_sym, kern_sym], grouped_conv_output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 3 False}(img, Subtensor{::, ::, ::int64, ::int64}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradinputs (test_corr.TestGroupCorr2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1618, in test_gradinputs
    grouped_func = theano.function([kern_sym, top_sym], grouped_conv_output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradInputs{valid, (1, 1), (1, 1), 3 False}(Subtensor{::, ::, ::int64, ::int64}.0, top, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradweights (test_corr.TestGroupCorr2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1569, in test_gradweights
    grouped_func = theano.function([img_sym, top_sym], grouped_conv_output, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradWeights{valid, (1, 1), (1, 1), 3 False}(img, kern, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_graph (test_corr.TestGroupCorr2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mutation\Desktop\theano-testcase\tests\test_corr.py", line 429, in test_graph
    gconv_func = theano.function([bottom_sym, kern_sym], conv_group, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 3 False}(bottom, Subtensor{::, ::, ::int64, ::int64}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_fwd (test_corr.TestUnsharedCorr2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1840, in test_fwd
    unshared_func = theano.function([img_sym, kern_sym], unshared_out_sym, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM{valid, (1, 1), (1, 1), 1 True}(img, Subtensor{::, ::, ::, ::, ::int64, ::int64}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradinput (test_corr.TestUnsharedCorr2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1920, in test_gradinput
    unshared_func = theano.function([kern_sym, top_sym], unshared_out_sym, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradInputs{valid, (1, 1), (1, 1), 1 True}(Subtensor{::, ::, ::, ::, ::int64, ::int64}.0, top, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

======================================================================
ERROR: test_gradweight (test_corr.TestUnsharedCorr2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 327, in filter
    converted_data = py_type(data)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\tensor\nnet\tests\test_abstract_conv.py", line 1876, in test_gradweight
    unshared_func = theano.function([img_sym, top_sym], unshared_out_sym, mode=self.mode)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function.py", line 317, in function
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\compile\function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\vm.py", line 1091, in make_all
    impl=impl))
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 955, in make_thunk
    no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 838, in make_c_thunk
    no_recycling=e_no_recycling)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 579, in accept
    self.fetch_variables()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\cc.py", line 605, in fetch_variables
    params = node.run_params()
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\graph.py", line 132, in run_params
    return self.op.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\op.py", line 809, in get_params
    return self.params_type.get_params(self)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in get_params
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\gof\params_type.py", line 448, in <dictcomp>
    for i in range(self.length)}
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\theano\scalar\basic.py", line 340, in filter
    type(data), data, self.dtype), e)
TypeError: ('The following error happened while compiling the node', CorrMM_gradWeights{valid, (1, 1), (1, 1), 1 True}(img, top, Elemwise{Cast{int64}}.0, Elemwise{Cast{int64}}.0), '\n', "Could not convert <class 'NoneType'> (value=None) to int64", TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",))

----------------------------------------------------------------------
Ran 34 tests in 28.901s

FAILED (errors=26)
